version: 2
jobs:
  build:
    docker: # Docker でステップを実行します
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run:
        name: rubocop
        command: bundle exec rubocop
